### ISSUE TITLE
Add Microdata (to RDF) parser?

### ISSUE THREAD

**Issue by danbri** [rdf-ext/rdf-ext#5]
There's a lot of Microdata out there (mostly schema.org); it parses to RDF fairly simply. Any plans for a parser? I don't have a tool to recommend, although http://www.milowski.com/journal/entry/2013-07-26T15:25:04.782Z/ might be interesting.

**Comment by elf-pavlik** [comment]
@bergos have you tried to parse RDFa with Green Turtle?
jsonld.js bundles it for that reason https://github.com/digitalbazaar/jsonld.js/blob/master/js/rdfa.js

**Comment by bergos** [comment]
@elf-pavlik the idea was first to add the Green Turtle Microdata parser with some small changes to RDF-Ext and than to reuse the patched code to get the RDFa parser running. But I had to patch so much in the Microdata parser that I decided to rewrite most of the code based on the spec. Now I'm not sure which version is better/worse, because writing the parser based on the spec wasn't a big success. Long story short: I'm working on the Microdata parser and than comes the RDFa parser on my todo list :-)

**Comment by elf-pavlik** [comment]
Wow! Looks like you have an adventure with this one @bergos :wink:

I think RDFa should make much less of a challenge since it boils down to parsing one of standard RDF serializations. See https://github.com/digitalbazaar/jsonld.js/blob/master/js/request.js#L117

Anyways, eventually I will need both to test examples in ActivityStreams2.0 specs https://github.com/jasnell/w3c-socialwg-activitystreams/issues/65 , but RDFa would give me third one for comparing with JSON-LD and Turtle...

**Comment by danbri** [comment]
So is the conclusion that green tortoise does not require a real browser DOM, just a basic .js environment?

**Comment by bergos** [comment]
@danbri Green Turtle requires DOM, but the https://www.npmjs.com/package/xmldom implementation can be used. xmldom was already in the RDF-Ext dependency list, because the RDF/XML parser also requires DOM.

**Comment by bergos** [comment]
@elf-pavlik I added a RDFa parser based on the JSON-LD code. At the moment it works only in a Node.js like environment. The JSON-LD require.js is a Node.js program. So I'm not sure if the JSON-LD code works without patching in the browser. Problem: The DOMParse class + .parseFromString method don't have a baseURI parameter, but the rdfa.js code requires a dom.baseURI or dom.location.href property, but that's read-only in the browser. Also language support doesn't work. I tried jsdom and xmldom. Sorry that I don't have a better solution at the moment. I hope it's usefull the way it is at the moment.

**Comment by elf-pavlik** [comment]
@bergos thank you! I just added few days ago a very rought parsing of RDFa to Activity Streams 2.0 spec in this commit https://github.com/elf-pavlik/w3c-socialwg-activitystreams/commit/4e79eb138157acd7f0157315de848bb8d22447ea

I'll try to talk with @alexmilowski and @davidlehn | @dlongley about creating proper NPM rdfa package based on green-turtle and also using it as dependency in jsonld
* https://github.com/alexmilowski/green-turtle/issues/3
* https://github.com/digitalbazaar/jsonld.js/issues/41#issuecomment-29796442
* https://lists.w3.org/Archives/Public/public-rdfjs/2014Jan/0014.html

cheers!

**Comment by bergos** [comment]
This issue was moved to rdf-ext/rdf-parser-microdata#1
